### PR TITLE
Fix #5

### LINKED ISSUE #5: Lines with only whitespace
The following demonstrates https://github.com/bbqsrc/xml-pretty/issues/3 exists here

```diff
diff --git a/src/document.rs b/src/document.rs
index 6ca1fa8..d0dc9ae 100644
--- a/src/document.rs
+++ b/src/document.rs
@@ -539,3 +539,18 @@ impl std::str::FromStr for Document {
         Self::from_reader(std::io::Cursor::new(s))
     }
 }
+
+#[cfg(test)]
+mod tests {
+    use std::str::FromStr;
+
+    use crate::Document;
+
+    #[test]
+    fn test_document_trailing_whitespace() {
+        let doc = Document::from_str(r#"<text>
+    Actual Output
+    </text>"#).unwrap();
+        assert_eq!(doc.to_string_pretty(), "<text>\n  \n    Actual Output\n    \n</text>\n");
+    }
+}
```

### PR DESCRIPTION
**Pull request by Ltrlg**
This PR fixes the whitespace increase in pretty mode reported in #5.

### CODE REVIEW

**Comment by jayvdb** [comment]
@bbqsrc , @Ltrlg , are we ready to do a release ?

**Comment by bbqsrc** [comment]
@Ltrlg I don't have a lot of time these days. Do you want to have publish rights for this repo?

**Comment by Ltrlg** [comment]
If that can help, yes. I can’t promise time and motivation beyond my use case, but I still have improvements that I plan to make (more docs, less panics, more tests, maybe a couple of API changes) and I enjoy fixing easy bugs like #5 was. (Looking at https://github.com/bbqsrc/xmlem/issues/11#issuecomment-2465114689, I may be a bit more interested in respecting XML than you are. Hopefully not enough to cause friction.)

**Comment by bbqsrc** [comment]
Nah it's perfectly complementary. I want to respect it while enabling "reality". I want both at the same time. The original purpose of this library was to enable XML 1.1 because I needed to represent nulls in XML becuase macOS's keyboard format does that. Then Android got in my way. So this entire library is pragmatism built on reality; conformance is the basis, utility is the goal.

**Comment by bbqsrc** [comment]
To put it differently: "I don't have time to respect it, please help." haha

**Comment by Ltrlg** [comment]
Seems fine, then.

**Comment by bbqsrc** [comment]
You have been invited to all the things, and you can do `cargo publish` once you accept the invites and I can add you to the release team :D

**Comment by Ltrlg** [comment]
Accepted. Did you forget to include [`qname`](https://github.com/bbqsrc/qname) in the org, or is there a reason I don’t see?

**Comment by bbqsrc** [comment]
... I forgot it existed. I'll move it over. :D

**Comment by Ltrlg** [comment]
@jayvdb With that underway, I plan to release a 0.3.0 with my recent changes once I will have added a few technically breaking changes to avoid needing a 0.4.0 too soon (as the pending changes are already breaking and for example adding options for #11 would currently be breaking).

I will then try to do the dependency upgrade in `xml-pretty`, which should not be too hard (but as I don’t yet know this codebase, it may take time at least to be comfortable with it).

**Comment by Ltrlg** [comment]
@bbqsrc Could you find the time to finish my integration? I cannot push to [`qname`](https://github.com/xmlem/qname) and am not part of the `xmlem/releases` team.

**Comment by bbqsrc** [comment]
@Ltrlg fixed :)

**Comment by Ltrlg** [comment]
@bbqsrc You did not add `xmlem/releases` as an owner for [`qname`](https://crates.io/crates/qname), [`qname-macro`](https://crates.io/crates/qname-macro) and [`qname-impl`](https://crates.io/crates/qname-macro), I cannot publish there.

**Comment by bbqsrc** [comment]
@Ltrlg omg. I do it now, sorry!

**Comment by bbqsrc** [comment]
It is done! Sorry for the inconvenience, it has been a bad few weeks. :)

**Comment by jayvdb** [comment]
@bbqsrc do you have all the permissions now?

**Comment by bbqsrc** [comment]
I think you mean @Ltrlg , and they do. 😊

**Comment by Ltrlg** [comment]
@jayvdb Yes, all works now: I just published `xmlem` 0.3. I’ve got little time available this month for `xmlem`, sorry about that. I will now look at `xml-pretty`, but I don’t think I will be able release a new version of it before January.

**Pull request merged**
