### PR TITLE
Fixes a few things, adds config "end_pad" and updates quick-xml to version 0.26

### PR DESCRIPTION
**Pull request by hoijui**
The fixes especially
are not necessarily done in the most elegant manner,
but they work for me.

### CODE REVIEW

**Comment by bbqsrc** [comment]
Thanks! :D

**Comment by hoijui** [comment]
ehh cool, thank you! :-)

**Comment by bbqsrc** [comment]
Published as 0.2.0

**Comment by hoijui** [comment]
I also updated your pretty-xml already .. will make PR there too

**Pull request merged**
